import streamlit as st
import joblib
import time

from utils import find_keywords, count_urls

# ==========================
# Sidebar
# ==========================
st.sidebar.title("📘 Project Information")

st.sidebar.write("### Developer")
st.sidebar.success("Shivam Gupta")

st.sidebar.write("### Dataset")
st.sidebar.info("CEAS_08")

st.sidebar.write("### Algorithm")
st.sidebar.success("Multinomial Naive Bayes")

st.sidebar.write("### Technology")
st.sidebar.write("""
- Python
- Streamlit
- Scikit-learn
- Pandas
- Joblib
""")

st.sidebar.write("### Version")
st.sidebar.success("1.0")

# ==========================
# Load Model
# ==========================
model = joblib.load("model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

# ==========================
# Main Title
# ==========================
st.title("📧 AI Email Phishing Detector")

st.markdown("""
### 🔒 AI Powered Email Security Scanner

This application detects whether an email is **Safe** or **Phishing**
using a Machine Learning model.

**Dataset:** CEAS_08

**Algorithm:** Multinomial Naive Bayes
""")

st.info("""
### 📊 Model Information

- Dataset : CEAS_08
- Algorithm : Multinomial Naive Bayes
- Task : AI Email Phishing Detection
- Language : Python
- Framework : Streamlit
""")

st.warning(
    "⚠️ This tool is for educational purposes only. "
    "Predictions are generated by a Machine Learning model "
    "and may not always be 100% accurate."
)

st.divider()

# ==========================
# User Input
# ==========================
st.write("### Enter Email Details")

subject = st.text_input("📌 Email Subject")

body = st.text_area("📄 Email Body", height=220)

# ==========================
# Sample Email
# ==========================
st.markdown("### 📌 Example Phishing Email")

st.code("""
Subject:
Urgent! Verify Your Account

Body:
Dear Customer,

Your account has been suspended.

Click the link below immediately.

http://fakebank-login.com

Thank You.
""")

# ==========================
# Prediction Button
# ==========================
if st.button("🔍 Analyze Email"):

    start = time.time()

    # Combine subject and body
    email = subject + " " + body

    # Find keywords and URLs
    keywords = find_keywords(email)
    urls = count_urls(email)

    # Convert text into numbers
    email_vector = vectorizer.transform([email])

    # Predict
    prediction = model.predict(email_vector)[0]

    # Confidence
    probability = model.predict_proba(email_vector)
    confidence = max(probability[0]) * 100

    end = time.time()

    st.divider()

    # ==========================
    # Prediction Result
    # ==========================
    st.subheader("Prediction")

    if prediction == 1:
        st.error("⚠️ This Email is PHISHING")
    else:
        st.success("✅ This Email is SAFE")

    st.write(f"**Confidence:** {confidence:.2f}%")

    st.progress(int(confidence))

    st.write(f"⏱ **Prediction Time:** {(end-start):.4f} seconds")

    # ==========================
    # Email Statistics
    # ==========================
    st.subheader("📊 Email Statistics")

    col1, col2, col3 = st.columns(3)

    col1.metric("Words", len(email.split()))
    col2.metric("Characters", len(email))
    col3.metric("URLs", len(urls))

    # ==========================
    # Analysis Report
    # ==========================
    st.subheader("📄 Analysis Report")

    st.write("### 🔍 Suspicious Keywords")

    if keywords:
        for word in keywords:
            st.write(f"• {word}")
    else:
        st.success("No suspicious keywords found.")

    st.write("### 🌐 URLs Detected")

    if urls:
        for url in urls:
            st.write(url)
    else:
        st.success("No URLs detected.")

    # ==========================
    # Risk Level
    # ==========================
    risk = len(keywords) + len(urls)

    st.subheader("🚨 Risk Level")

    if risk >= 5:
        st.error("🔴 HIGH")
    elif risk >= 2:
        st.warning("🟡 MEDIUM")
    else:
        st.success("🟢 LOW")

st.divider()

st.caption("Developed by Shivam Gupta | Major Internship Project | 2026")